baseURL = "https://billett.me"
languageCode = "en-uk"
title = "Ian Billett"
theme="archie"
copyright = "© Ian Billett"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=100 # articles per page

# Number of characters to show in summary.
summaryLength = 20

[params]
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=true

	# Custom list of Javascript files to load. Just like custom CSS you can place js files under
    # `static/js` folder and specify path here as `js/script-name.js`. You can also specify full url,
    # for example you may want to include external JS library.
    customJS = ["https://www.googletagmanager.com/gtag/js?id=G-XRDKBSCP62", "/js/google-analytics.js",]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/bill3tt"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/billett_"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ian-billett-5501a35a/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

# Enable tags.
[taxonomies]
   tag = "tags"